name       : ovmf
version    : '202108'
release    : 5
source     :
    - git|https://github.com/tianocore/edk2 : edk2-stable202108
license    : 
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Python-2.0
    - Zlib
component  : virt
summary    : EDK II based project to enable UEFI support for Virtual Machines
description: |
    OVMF is an EDK II based project to enable UEFI support for Virtual Machines. OVMF contains sample UEFI firmware for QEMU and KVM.
    To use directly with qemu make VM specific copys of 'OVMF_VARS.fd' so uefi variables can be writen.
builddeps  :
    - acpica-unix
    - pkgconfig(python3)
setup      : |
   %apply_patches 
build      : |
    make %JOBS% -C BaseTools
    . edksetup.sh
    sed s/'MAX_CONCURRENT_THREAD_NUMBER = 1'/'MAX_CONCURRENT_THREAD_NUMBER = '%YJOBS%/ $pkgfiles/target.txt > $workdir/Conf/target.txt
    build
install    : |
    install -Dm 0644 $workdir/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_CODE.fd $installdir/usr/share/OVMF/OVMF_CODE.fd
    install -Dm 0644 $workdir/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_VARS.fd $installdir/usr/share/OVMF/OVMF_VARS.fd
    install -Dm 0644 $workdir/License.txt $installdir/usr/share/OVMF/edk2_License.txt
    install -Dm 0644 $workdir/OvmfPkg/License.txt $installdir/usr/share/OVMF/OvmfPkg_License.txt
