name       : ovmf
version    : 2017
release    : 1
source     :
    - https://github.com/tianocore/edk2/archive/vUDK2017.tar.gz : 67bef685122661955a1e84768adeb06d8433175ee2d98ee66facdba74621dd27
license    : |
    - BSD-2-Clause
    - BSD-3-Clause
    - MIT
    - Python-2.0
    - Zlib
component  : virt
summary    : EDK II based project to enable UEFI support for Virtual Machines
description: |
    OVMF is an EDK II based project to enable UEFI support for Virtual Machines. OVMF contains sample UEFI firmware for QEMU and KVM.
    To use directly with qemu make VM specific copys of 'OVMF_VARS.fd' so uefi variables can be writen.
builddeps  :
    - acpica-unix
    - pkgconfig(python-2.7)
setup      : |
    %patch -p1 < $pkgfiles/FixRaceBaseTools.patch
build      : |
    make %JOBS% -C BaseTools
    . edksetup.sh
    sed s/'MAX_CONCURRENT_THREAD_NUMBER = 1'/'MAX_CONCURRENT_THREAD_NUMBER = '%YJOBS%/ $pkgfiles/target.txt > $workdir/Conf/target.txt
    build
install    : |
    install -Dm 0644 $workdir/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_CODE.fd $installdir/usr/share/OVMF/OVMF_CODE.fd
    install -Dm 0644 $workdir/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_VARS.fd $installdir/usr/share/OVMF/OVMF_VARS.fd
    install -Dm 0644 $workdir/FatPkg/License.txt $installdir/usr/share/OVMF/FatPkg_License.txt
    install -Dm 0644 $workdir/OvmfPkg/License.txt $installdir/usr/share/OVMF/OvmfPkg_License.txt
